import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import MenuComponent from "@/components/MenuComponent";
import SideComponent from "@/components/Index/SideComponent";
import CategoryComponent from "@/components/Index/CategoryComponent";
import FooterComponent from "@/components/FooterComponent";
import WorkersComponent from "@/components/Index/WorkersComponent";
import {
  useAuthUser,
  withAuthUser,
  withAuthUserTokenSSR,
} from "next-firebase-auth";
import { useEffect } from "react";
import { useRouter } from "next/router";

const Home = () => {
  const user = useAuthUser();
  const router = useRouter();
  useEffect(() => {
    if (user.id) {
      const fetchUser = async () => {
        const userResponse = await fetch(`/api/user/${user.id}`, {
          method: "GET",
        });
        const userDetail = await userResponse.json();
        if (!userDetail) {
          router.push("/profile/update-info");
        }
      };
      fetchUser();
    }
  }, [user]);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MenuComponent user={user} />
      <SideComponent />
      <div className="container mx-auto px-3 md:px-0">
        <CategoryComponent />
        <WorkersComponent />
      </div>
      <FooterComponent />
    </>
  );
};
export const getServerSideProps = withAuthUserTokenSSR()();

export default withAuthUser()(Home);
